Flask 2: https://replit.com/@A-Ufret/CSSJWarriorsFlask#main.py

* Instructions: If you're using repl.it (the recommended method), make your site on repl.it, make sure it's public and add the repl.it repl link to the
README.org file in the flask folder of your repo. In either case, list all routes you've created in the README.org file. (Assigned 2/9/23)

2/15/23 
By: Ashley Ufret & Théa Williams
Flask Website Assignment Pt 1: Link (Replit): https://replit.com/@theawilliams19/CS-Social-Justice-Warriors-Website-with-Flask

routes:
app.route('/') def index():
@app.route('/about')
@app.route('/plhistory')
@app.route('/news')
@app.route('/upcoming')
@app.route('/contactus')
@app.route('/challenge') *Random Number for Advocacy Challenge
  
** If you are presenting this unit: No

*** Upload instructions
Upload all content relating to the delivery of your unit. Include the
prework, slides, content etc.

Please use these filenames:
- *homework.md*, *homework.pdf*, or *homework.docx* for the homework
  assignment
- *prework.md*, *prework.pdf*, or *prework.docx* if you are giving
  links to videos or online resources for prework
- Other files should be given names that make sense
*** Assigning the work
- make sure to post the prework one week before your presentation in
  the #cstopics-async channel.
- make sure to post the homework after your group presentation in the
  #cstopics-hw channel.
  
** If you are completing the homework for this unit:

The homework will be posted in the #cstopics-hw channel.

Upload your solutions to the assigned homework in the appropriate
folder. Make sure to use the filenames specified in the assignments.

