Ashley Ufret

Encryption Non-pke Howework

Part 1: Decoding a Message using a shift (Caesar) cipher
https://replit.com/@A-Ufret/DecryptionHW#main.py

Part 2: Encoding a Message
Encryption with custom Substitution Cypher
  1. Write a secret message to encode
  2. Set a custom key for the alphabet string
  3. Def(encrypt) set index values = char so that it looks for the index value of each character in the message in the 'alphabet' string
  4. Join indexkey for indexkey in values so that it returns the value of each character of the message that is in the same index of the key
  5. Def(decrypt) start with  indexValues = [key.index(char) for char in encryptedText] so that it looks for the index of each character of the encrypted message in      the key
  6. Return join(alphabet[indexKey] for index key in index values so it replaces each character of the encrypted message with the character from the 'alphabet string'    whose index matches with the5.
  7. encryptedtext = encrypt() to store the encrypted message
  8. Print "" encrypted text so that it prints the encrypted message 
  9. Last you can print the decrypted message to confirm it is working correctly 
  10. Example of what the code would look like https://replit.com/@A-Ufret/EncryptionHW#Encrytion.py







* Instructions

** If you are presenting this unit:

*** Upload instructions
Upload all content relating to the delivery of your unit. Include the
prework, slides, content etc.

Please use these filenames:
- *homework.md*, *homework.pdf*, or *homework.docx* for the homework
  assignment
- *prework.md*, *prework.pdf*, or *prework.docx* if you are giving
  links to videos or online resources for prework
- Other files should be given names that make sense
*** Assigning the work
- make sure to post the prework one week before your presentation in
  the #cstopics-async channel.
- make sure to post the homework after your group presentation in the
  #cstopics-hw channel.
  
** If you are completing the homework for this unit:

The homework will be posted in the #cstopics-hw channel.

Upload your solutions to the assigned homework in the appropriate
folder. Make sure to use the filenames specified in the assignments.

